version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sofy-music-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - RATE_LIMIT_PER_MINUTE=60
      - MAX_CONCURRENT_REQUESTS=10
      - REQUEST_TIMEOUT=300
      - RETRY_ATTEMPTS=3
      - RETRY_DELAY=1
      - ENABLE_METRICS=true
      - ENABLE_LOGGING=true
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
    networks:
      - sofy-music-net

  mongo:
    image: mongo:latest
    container_name: sofy-music-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - sofy-music-net

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: sofy-music-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - sofy-music-net

  grafana:
    image: grafana/grafana-oss:10.1.5
    container_name: sofy-music-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - sofy-music-net

volumes:
  prometheus-data: {}
  grafana-storage: {}
  mongo-data: {}

networks:
  sofy-music-net:
    driver: bridge 